[package]
name = "collections"
version = "0.1.0"
authors = ["Kevin Languasco <3322228+kevinalh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
